### ISSUE TITLE
rexml/document not installed but rexml/document doesn't exist

### ISSUE THREAD

**Issue by Rozendantz** [ruby/rexml#76]
Having this issue on Arch Linux, whenever I run cewl I get the following output:

```
CeWL 5.5.2 (Grouping) Robin Wood (robin@digi.ninja) (https://digi.ninja/)

Error: rexml/document gem not installed
	 use: "gem install rexml/document" to install the required gem

```
If I try to install as per the instructions I get the following output:

```
$ gem install rexml/document
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Not Found 404 (https://index.rubygems.org/info/rexml/document)

```

~/.local/share/gem/ruby/3.0.0/bin is in my PATH

**Comment by olleolleolle** [comment]
@Rozendantz Hi, I took a look at the cewl script, which seems to be developed with Ruby 2.5 (Dockerfile had that). In that version of Ruby, rexml was a standard library, always included with Ruby. From 3.0 and onwards, it must be added like another gem.

The fix is: include `gem "rexml"` in the Gemfile. https://github.com/digininja/CeWL/blob/2e8d24f9b1e9bdc8bc905d3a6dd9fa76bbb4055c/Gemfile perhaps inside a RUBY_VERSION check, only adding it when it does not come bundled with the running Ruby.

Hope this helps, this is not a defect in rexml. 👋
